### ISSUE TITLE
Provide a more pratical Getting Started page

### ISSUE THREAD

**Issue by kennydude** [thephpleague/route#15]
[This page](http://route.thephpleague.com/getting-started/) describes how to get the router to work for one route.

Personally I think it would be a bit more useful to have an example which shows how to typically use the router, via the URL actually requested etc.

**Comment by philsturgeon** [comment]
PR? :)

**Comment by philipobenito** [comment]
:+1: aiming at padding out the docs but more than happy to take pull requests in this area too :-)

**Comment by tpavlek** [comment]
I'd like to submit a PR for this, but I really don't understand how this is intended to work?

Are there any projects implementing this?

**Comment by philipobenito** [comment]
Well it can be used to build an application, it's a lightweight routing layer with the aim of allowing users to essentially build their own framework around what they are building.

Some have build micro-frameworks around it:
Proton: https://github.com/alexbilbie/Proton

There is also a restful API framework built on top of it but I forget the name. 

The point though is that the way the climate in the community is going and with the rise of package managers, this gives you the option to build around it with the packages you need for specific applications rather than relying on a full stack framework.

**Comment by tpavlek** [comment]
Oh yes, sorry I was unclear.

I absolutely know and understand the purpose of a router.

Specifically, I don't understand the syntax of adding multiple routes. Am I supposed to be computing the URL inputted to determine what to dispatch? Do any of the strategies handle automatic dispatching when multiple routes are configured.

I just don't understand the specific syntax that's intended to be used when this package is used in nontrivial cases.

**Comment by philipobenito** [comment]
Well I'm actually building an application right now so can provide you with an example over the next few days. At the moment you define as many routes as you wish and pass the request uri and request method to the dispatcher, a route will be matched and the callable attached to that will be invoked. There is a plan to auto dispatch from a request object once PSR-7 is complete but for now there are no restrictions on how you gather the information needed, whether that be from a Request based object or even the `$_SERVER` array....

**Comment by tpavlek** [comment]
I updated some docs with what I've understood at this point in PR #18.

Let me know if any of my assumptions are incorrect or if the style is inappropriate for the docs.

**Comment by philipobenito** [comment]
Brilliant stuff, thank you, I'll take a proper look tomorrow morning as there are a few small examples I'd like to link to etc but don't have them with me right now.

:+1:
