### ISSUE TITLE
Adding additional Route Conditions?

### ISSUE THREAD

**Issue by geeShoe** [thephpleague/route#170]
Is it possible to add additional route conditions. I.e. server port. 

I see in the RouteConditionTrait.php, you can get/set Host, Name, and Scheme. I'm working on an app that uses the same host and scheme but one part of the app uses tcp80 and the other uses tcp say 81. 

Currently using If/else statements when defining the route map depending on the value of  $_SERVER['SERVER_PORT'] to direct to the appropriate group. Is there a cleaner way to do this that i'm missing or any plans in a future implementation down the road?

**Comment by philipobenito** [comment]
Had to delay replying to this last night because I was convinced this was already implemented, no idea why I left it out, I have a new major release drafted in for around Easter, but there is nothing stopping this being added as a minor version too, I'm a bit tight on time so a PR would be welcome, if not I'll get to it as I finish off the new major. :-)

**Comment by philipobenito** [comment]
Fixed by #171
