### ISSUE TITLE
Provide PSR15 dispatcher out of the box

### ISSUE THREAD

**Issue by kdubuc** [thephpleague/route#261]
Hi all,

Why not provide out of the box a basic Middleware to dispatch the request into the League's Router in a PSR15 fashion :

```php
final class DispatcherMiddleware implements MiddlewareInterface
{
    /**
     * Assign League's Router in the middleware.
     */
    public function __construct(Router $router)
    {
        $this->router  = $router;
    }

    /**
     * Process an incoming server request and dispatch it in the router.
     */
    public function process(ServerRequestInterface $server_request, RequestHandlerInterface $handler) : ResponseInterface
    {
        return $this->router->dispatch($server_request);
    }
}
```

If it's okay, I can PR this !

**Comment by philipobenito** [comment]
I'm not sure what benefit this would provide other than pushing an existing middleware pipeline (the dispatcher) through a different middleware pipeline, unless I'm missing something?

**Comment by kdubuc** [comment]
With [Zend stratigility](https://github.com/zendframework/zend-stratigility), I used to pipe some middlewares (```MiddlewareInterface```) like auth, json payload, and so on in my HTTP Pipeline. The latest brick in my app is the router, and I found convenient to pipe the dispatcher like others middlewares. (aka ```$http_pipeline->pipe(new DispatcherMiddleware($router))```).

If I am correct, the dispatcher is only a Request Handler.

But, it's possible that *I'm* missing something  !

**Comment by philipobenito** [comment]
Route is also a middleware pipeline so you don't need a separate one.

Take a look here to see if we're on the same page: https://route.thephpleague.com/4.x/middleware/

Let me know if it's still not what you're trying to achieve and we can discuss some more.

**Comment by kdubuc** [comment]
Actually, I did not have considered to replace Stratigility with Route. It's a possibility.
But, with the dispatcher as a middleware, we can combine the two (router and another RequestHandler) seamlessly, but i'm not sure it is the target of this project.
Thank you for yours replies ! I can close the issue for now if it's okay for you.

**Comment by delboy1978uk** [comment]
Currently the Dispatcher finds a route match and sets that as the middleware. However attempting a route match is the first thing to happen, so i can't use for instance i18n middleweare that for example would set the locale as a request attribute whilst stripping the locale from the uri itself.
Imagine my route is `/en_GB/profile` versus `/profile. Currently that will 404 because routing has to happen first.

If router were to implement the RequestHandlerInterface, then it could be passed into other middleware stacks in front of it, allowing the likes of the example i18n middleware to work. The dispatch method is essentially the handle method with a different name.

```
/**
     * {@inheritdoc}
     */
    public function dispatch(ServerRequestInterface $request): ResponseInterface
    {
        return $this->handle($request);
    }


    /**
     * {@inheritdoc}
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        if ($this->getStrategy() === null) {
            $this->setStrategy(new ApplicationStrategy);
        }

        $this->prepRoutes($request);

        /** @var Dispatcher $dispatcher */
        $dispatcher = (new Dispatcher($this->getData()))->setStrategy($this->getStrategy());

        foreach ($this->getMiddlewareStack() as $middleware) {
            if (is_string($middleware)) {
                $dispatcher->lazyMiddleware($middleware);
                continue;
            }

            $dispatcher->middleware($middleware);
        }

        return $dispatcher->dispatchRequest($request);
    }
```

The alternative is to have a pre-route stack in the router itself. I'll wait for your feedback before coding anything if need be.
