### ISSUE TITLE
Allow for empty route paths to be treat as the base route path

### ISSUE THREAD

**Issue by kimjohans** [thephpleague/route#322]
Removed request. Please close issue. Thanks.

**Comment by philipobenito** [comment]
I'll have to double check this in a few days but if I remember correctly it's not expecting an empty route path, by design it's expecting "/" for an empty/base route path and then it would match. 

Your proposed change might be considered a breaking change but I'll look in to it more when I'm back on a computer.

**Comment by kimjohans** [comment]
I have checked it with using "/" in all empty definitions/paths and it seems to work.
Looks only confusing, because every developer is thinking, the path is "//" ...
So no bug, just a feature / optimization

**Comment by philipobenito** [comment]
Yeah, empty just wasn't considered that's all, something I'll probably account for in the next major version, can't right now as it could change behaviour of other peoples apps
