### ISSUE TITLE
Can't dispatch more than once on same RouteCollection

### ISSUE THREAD

**Issue by thebigb** [thephpleague/route#75]
*This is regarding the develop branch*

When I try to dispatch more than once on the same `RouteCollection` instance, I get the following exception:
```
FastRoute\BadRouteException: Cannot register two routes matching "/" for method "GET" in /home/ubuntu/workspace/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php on line 55
```

If it's not intended to do so, this behaviour should probably be documented.

I can probably work around this with a factory of some sorts, but it would be neat if it was supported.

Minimal testcase:
```
use League\Route\RouteCollection;
use Zend\Diactoros\Response;
use Zend\Diactoros\ServerRequest;
use Zend\Diactoros\Uri;

$routes = new RouteCollection();
$routes->get('/', function() { return 'foo'; });

$routes->dispatch((new ServerRequest())->withUri(new Uri('/')), new Response());

$routes->dispatch((new ServerRequest())->withUri(new Uri('/')), new Response());
```

**Comment by philipobenito** [comment]
It's not something that is intended. Once documentation is written then it will include a section on this.


What is your use case to dispatch twice?

**Comment by thebigb** [comment]
My main use case at the moment is unit testing. I generate various requests
and run them against the same RouteCollection.

Another use case could be internal routing to achieve something like HMVC (
https://en.m.wikipedia.org/wiki/Hierarchical_model–view–controller).

**Comment by philipobenito** [comment]
Well the issue here is less the dispatch but the fact that the underlying router (FastRoute) does not allow matching twice so it's not something I can implement in the manner you describe.


When it comes to unit tests, my personal opinion is that if you're routing, then it's not a unit test really, unit test the controller callable and let your other test suites look after routing or trust that the router is unit tested to ensure your routes will be matched.




That being said, by using named routes you can achieve what you want to achieve by just pulling the route from the collection and dispatching the route directly. Handling it this way also has the benefit of not relying on paths, so they can change without having to then reactor where you're dispatching them from.

**Comment by thebigb** [comment]
Fair enough, I'll try that.

**Comment by hannesvdvreken** [comment]
Too bad it's because of fastroute. Would be nice to use league/route in a reactphp powered application or something, where the router object is reused for every request

**Comment by thebigb** [comment]
You still can, but you'll have to build a wrapper around the dispatch method that creates a new `RouteCollection` and loads the routes for each dispatch.

**Comment by hannesvdvreken** [comment]
Well, that's exactly what you would want to avoid :-)
