### ISSUE TITLE
Container dependency

### ISSUE THREAD

**Issue by designermonkey** [thephpleague/route#86]
As the code only passes the Container instance down the chain to a Strategy, which itself only uses the `get` method, it would make sense to not rely on a hard dependency of the League Container, and rather replace this dependency with a dependency on the Interop Container instead.

This would make the code much freer from having to use a container that developers may not be using, and increase uptake of the package.

Personally, I am a fan of Auryn Injector, and could very easily make a very simple bridge for Auryn to the package, if only it relied on the Interop Container instead of the League one.

I understand that a custom Strategy can be made that relieves the reliance, but still, an instance of a Container is still created and passed around that is not always required. Call me weird, but this just doesn't feel right to me.

**Comment by philipobenito** [comment]
This is a simple question of barrier to entry that's been discussed many times.

Whilst I agree with you that in an ideal world the dependency would not be directly on league/container, I disagree that it would increase uptake, I think it would be the opposite.

The recent change to PSR-7 dependency with no implementation is already a larger barrier to entry than I'd like in a perfect world, but it is ultimately a necessary evil, more so than the removal of league/container.

Instantiation is inexpensive so I don't really see that as too much of an issue. Specifically, the league ContainerInterface is used instead of container interoperability because of the reliance on the call method, a bridge can still easily be written though if that initial instantiation bothers you. Otherwise, any container can be used directly with a custom strategy as you're already aware.

I thank you for your input, however, as also discussed on other threads, this isn't something I will be changing for the upcoming major release. It will be reevaluated at the time of the next major release.
