### ISSUE TITLE
[Feature Request] Nested route groups

### ISSUE THREAD

**Issue by Eragon666** [thephpleague/route#96]
Hi all,

I am trying v2 for my application. I really like the route groups, but I couldn't figure out a way to build nested route groups. 

I tried to just simply nest it 

```php

$router = new RouteCollection($container);

$router->group('/admin', function($router) {

    $router->map(...);

    $router->group('/cms', function($router) {
        $router->map(...);
        $router->map(...);
    });

});

```

But I get the error (for the nested group):

```php
Fatal error: Call to undefined method League\Route\RouteGroup::group()
```

So I think nested routing is not supported, is this possible to implement?

**Comment by philipobenito** [comment]
It's not something that is planned for 2.0.0, however it maybe be something that we look at going forward.

**Comment by Eragon666** [comment]
Do you think that it is something that coule be implemented without to much effort?

If so, I will try if I can implement it myself :)

-------- Original Message --------

**Comment by philipobenito** [comment]
I think there is probably quite a large level of complexity at first look, the issue here is that a nested group can then have a nested group, then that nested group can have a nested group, so there are considerations to be made around that, it also will probably be required to be explicitly defined as a nested group so that it can inherit the parents prefix.

More than happy for you to have a go at it, then we'll look through it and address any complexities for the next feature release.

**Comment by Eragon666** [comment]
I will try to take a look at this feature in the Christmas holiday. 

If you have any tips/recommendations or anything else please let me know!

**Comment by philipobenito** [comment]
:+1:

**Comment by alexrohleder96** [comment]
And if the `group` method receive an array instead of a closure, as all mapping methods return a `Route` object that can alter the `path` attribute, the nesting can be done easily. eg.

```php
$router->group('/admin', [
    $router->get('/', '...'),
    $router->group('/cms', [
        $router->get('/posts', '...')
    ])
]);
```
PHP will first register `/` and the inner `/posts`, so the inner group will change the `/posts` to `/cms/posts`, and at the end the outer group will prefix all these routes passed as parameter with `/admin`.

This idea is simple and needs a little refactoring, but will allow a big flexibility in registering routes. If accepted I could implement that and request a pull.

**Comment by philipobenito** [comment]
That would actually require an overall of the group system because using the closure, the routes are actually registered on the group object, not the router itself

**Comment by mbunge** [comment]
We could work with a level indicator, similar to transaction nesting levels. But in this case I would prefer a NestedRouteGroup extending the RouteGroup

**Comment by philipobenito** [comment]
I feel like the benefit this provides isn't worth the complexity it introduced. For the example above I think a nicer way of handling it for readability would be to have multiple groups anyway.
